name: Jenkins Job Conversion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      subscription_id:
        description: 'Azure Subscription Id'
        required: true
        type: string
      tenant_id:
        description: 'Azure Tenant Id'
        required: true
        type: string
      application_id:
        description: 'Azure Application Id'
        required: true
        type: string
      application_password:
        description: 'Azure Application Password'
        required: true
        type: string
      azure_registry_name:
        description: 'Azure Registry Name'
        required: true
        type: string
      azure_repo_name:
        description: 'Azure Repo Name'
        required: true
        type: string
      docker_image_name:
        description: 'docker image name'
        required: true
        type: string
      docker_image_tag:
        description: 'docker image tag'
        required: true
        type: string
      acr_docker_image_tag:
        description: 'azure docker image tag'
        required: true
        type: string
      opsera_pipeline_id:
        description: 'Opsera pipeline id'
        required: true
        type: string
      opsera_step_id:
        description: 'Opsera step id'
        required: true
        type: string
      opsera_pipeline_run_count:
        description: 'Opsera pipeline run count'
        required: true
        type: string
      file_name:
        description: 'Opsera docker file name tar'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{ "clientId": "${{ secrets.APPLICATION_ID }}", "clientSecret": "${{ secrets.APPLICATION_PASSWORD }}", "tenantId": "${{ secrets.TENANT_ID }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}" }'

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ github.event.inputs.azure_registry_name }}

      - name: Load Docker Image
        run: |
          docker load --input /home/runner/work/.docker-images/${{ github.event.inputs.file_name }}.tar

      - name: Tag Docker Image
        run: |
          docker tag ${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.docker_image_tag }} ${{ github.event.inputs.azure_registry_name }}.azurecr.io/${{ github.event.inputs.azure_repo_name }}:${{ github.event.inputs.acr_docker_image_tag }}

      - name: Push Docker Image
        run: |
          docker push ${{ github.event.inputs.azure_registry_name }}.azurecr.io/${{ github.event.inputs.azure_repo_name }}:${{ github.event.inputs.acr_docker_image_tag }}

    env:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PASSWORD: ${{ secrets.APPLICATION_PASSWORD }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}